name: "Build halium-boot and system images"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: "C"
      USE_HOST_LEX: "yes"
      TEMPORARY_DISABLE_PATH_RESTRICTIONS: "true"
    steps:
      - name: "Add 32-bit architecture"
        run: "sudo dpkg --add-architecture i386"
      - name: "Install dependencies"
        run: "sudo apt install git gnupg flex bison gperf build-essential zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool liblz4-tool bc lzop imagemagick libncurses5 rsync python-is-python3 repo"
      - name: "Initialize repo"
        run: "repo init -u https://github.com/j1xlte-gtelwifiue/halium -b halium-10.0 --depth=1"
      - name: "Download halium sources"
        run: "repo sync -c -j 16"
      - name: "Download j1xlte sources"
        run: "./halium/devices/setup j1xlte"
      - name: "Remove unnecesary patch"
        run: "rm hybris-patches/external/v8/0001-blueprints-Allow-building-on-both-Linux-and-macOS.patch"
      - name: "Apply hybris patches"
        run: "./hybris-patches/apply-patches.sh --mb"
      - name: "Download initramfs"
        run: "./device/samsung/j1xlte/update-initramfs.sh"
      - name: "Setup environment"
        run: "source build/envsetup.sh"
      - name: "Setup environment for j1xlte"
        run: "breakfast j1xlte"
      - name: "Create missing directory"
        run: "mkdir -p out/target/product/j1xlte/recovery/root/system/etc"
      - name: "Build mkbootimg"
        run: "mka mkbootimg"
      - name: "Build halium-boot"
        run: "mka halium-boot"
      - name: "Build e2fsdroid"
        run: "mka e2fsdroid"
      - name: "Build systemimage"
        run: "mka systemimage"
      - name: Upload halium-boot.img
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: "halium-boot.img" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "out/target/product/j1xlte/halium-boot.img"
      - name: Upload system.img
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: "halium-boot.img" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "out/target/product/j1xlte/system.img"
